name: 'workflow-matrix'
description: Generate build matrix from yaml file
author: Dmytro Bondar

branding:
  icon: grid
  color: green

inputs:
  matrix-file:
    description: 'YAML file with matrix'
    required: false
    default: '.github/workflow-matrix.yml'
  workflow:
    description: 'workflow name to get matrix'
    required: false
    default: '${{ github.workflow }}'
outputs:
  matrix:
    description: 'Output generated matrix for workflow'
    value: ${{ steps.script.outputs.matrix }}

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v6
      id: script
      with:
        script: |
          const yaml = require('yaml');
          const matrixFile = core.getInput('matrix-file');
          const workflow = core.getInput('workflow');

          let response = await github.rest.repos.getContent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: matrixFile,
            ref: context.sha
          });
          // Parse the response and print the YAML file content to the console
          let content = Buffer.from(response.data.content, 'base64').toString('utf8');
          console.log(content);

          // Read and parse matrix-file
          const mergeResult = yaml.parse(content, { merge: true });

          // Get matrix for current workflow with fallback to default matrix
          var matrix = {};
          if (workflow in mergeResult) {
              console.log(`Use ${workflow} matrix`);
              matrix = JSON.stringify(mergeResult[workflow].matrix);
          } else {
              console.log(`Use default matrix`);
              matrix = JSON.stringify(mergeResult.matrix);
          };

          // Set matrix output
          core.setOutput("matrix", matrix ? matrix : {});
